stages:
  - deploy

deploy-to-production:
  stage: deploy
  only:
    - master
  tags:
    - runner-asset    # ใช้ Tag เดิมของโปรเจค asset_it-frontend
  script:
    - cd /var/www/jastel-app/asset_it/asset_it-frontend
    - git fetch origin master
    - git reset --hard origin/master
    - docker network inspect jastel-network >/dev/null 2>&1 || docker network create jastel-network
    - docker compose up -d --build
    - docker image prune -f
    - docker builder prune -f